#!/bin/bash
#
# Git hook to update scoring keywords after content changes
# This should be run as a pre-push or post-commit hook
#

echo "🔄 Updating scoring keywords from content tags..."

# Change to backend directory
cd "$(dirname "$0")" || exit 1

# Run the tag extraction script
python3 extract_tags.py

# Check if keywords file was modified
if git diff --quiet scoring_keywords.json; then
    echo "✅ No keyword changes needed"
else
    echo "📝 Keywords file updated with new tags"
    echo "🔍 Changes:"
    git diff --no-index /dev/null scoring_keywords.json | grep "^+" | head -5
    
    # Optionally auto-commit the changes
    read -p "🤔 Auto-commit keyword updates? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git add scoring_keywords.json
        git commit -m "chore: update technical skills keywords from content tags

🤖 Auto-generated by extract_tags.py

Co-Authored-By: Claude <noreply@anthropic.com>"
        echo "✅ Committed keyword updates"
    else
        echo "⏭️  Skipped auto-commit (you can commit manually later)"
    fi
fi

echo "🎉 Keyword update complete!"